version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8070:8070"
    volumes:
      - ".:/app"
    container_name: discord-bot
    command: tail -f /dev/null