version: '3'
services:
  discord-bot:
    build: ./discord_bot/.
    ports:
      - "8070:8070"
    volumes:
      - "./discord_bot/.:/app"
    networks:
      discord:
        ipv4_address: 10.10.0.2
    command: node index.js --reload
  
  transcription-service:
    build: ./transcription_service/.
    ports:
     - "8010:8010"
    volumes:
      - "./transcription_service/.:/app"
    networks:
      discord:
        ipv4_address: 10.10.0.3
    command: python3 handle_packet.py --reload

networks:
  discord:
    ipam:
      driver: default
      config:
      - subnet: "10.10.0.0/16"
