version: '3'
services:
  discord-bot:
    build: ./discord_bot/.
    ports:
      - "8070:8070"
    volumes:
      - "./discord_bot/.:/app"
    networks:
      discord:
        ipv4_address: 10.10.0.2
    container_name: bot
    command: tail -f /dev/null

  transcription:
    build: ./transcription_service/.
    ports:
      - "8010:8010"
      - "8000:8000"
    volumes:
      - "./transcription_service/.:/app"
    networks:
      discord:
        ipv4_address: 10.10.0.3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    container_name: transcription
    command: tail -f /dev/null
  
networks:
  discord:
    ipam:
      driver: default
      config:
      - subnet: "10.10.0.0/16"
