version: '3'
services:
  discord-bot:
    build: ./discord_bot/.
    ports:
      - "8070:8070"
    volumes:
      - "./discord_bot/.:/app"
    networks:
      discord:
        ipv4_address: 10.10.0.2
    container_name: bot
    command: tail -f /dev/null

  transcription-service-cpu:
    build:
      context: ./transcription_service
      dockerfile: Dockerfile-cpu
    ports:
      - "8010:8010"
    volumes:
      - "./transcription_service/.:/app"
    networks:
      discord:
        ipv4_address: 10.10.0.3
    profiles:
      - cpu
    container_name: transcription
    command: tail -f /dev/null
  
  transcription-service-gpu:
    build:
      context: ./transcription_service
      dockerfile: Dockerfile-gpu
    ports:
      - "8010:8010"
    volumes:
      - "./transcription_service/.:/app"
    networks:
      discord:
        ipv4_address: 10.10.0.3
    profiles:
      - gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    container_name: transcription
    command: tail -f /dev/null

networks:
  discord:
    ipam:
      driver: default
      config:
      - subnet: "10.10.0.0/16"
