version: '3'
services:
  discord-bot:
    build: ./discord_bot/.
    ports:
      - "8070:8070"
    volumes:
      - "./discord_bot/.:/app"
    command: tail -f /dev/null
  
  transcription-service:
    build: ./transcription_service/.
    ports:
     - "8090:8090"
    volumes:
      - "./transcription_service/.:/app"
    command: tail -f /dev/null
    # profiles: ['transcription']
